name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
           
      - name: 1. Descargar codigo
        uses: actions/checkout@v4

      - name: 2. Instalar Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 3. Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 4. Instalar Cordova
        run: npm install -g cordova

      - name: 5. Añadir plataforma Android
        run: |
          # Instalamos la versión más estable para 2026
          cordova platform add android@13.0.0 --save

      - name: 5.5 Prepare Platform
        run: cordova prepare android
        
      - name: 6. Parchear Plugin BarcodeScanner y Fix SDK
        run: |
          # 1. Reemplazar 'compile' por 'implementation' en cualquier archivo gradle
          find platforms/android/ -name "*.gradle" -exec sed -i 's/compile(/implementation(/g' {} +
          find platforms/android/ -name "*.gradle" -exec sed -i 's/compile /implementation /g' {} +
          
          # 2. Inyectar variables de SDK en gradle.properties
          # El archivo suele estar en platforms/android/gradle.properties
          [ -f platforms/android/gradle.properties ] && echo "cdvCompileSdkVersion=34" >> platforms/android/gradle.properties
          [ -f platforms/android/gradle.properties ] && echo "cdvTargetSdkVersion=34" >> platforms/android/gradle.properties
          
          # 3. Localizar y dar permisos a gradlew de forma recursiva
          # Esto evita el error de "No such file or directory"
          find platforms/android/ -name "gradlew" -exec chmod +x {} +
          
      - name: 7. Compilar APK
        run: cordova build android --debug --device --no-telemetry
        
      - name: 8. Subir APK resultante
        uses: actions/upload-artifact@v4
        with:
          name: Hydra-Debug-APK
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
